package cvar

const (
	TOPICS_FLOW_END_QUEUE                    = "bgd-flow-endqueue"
	TOPICS_CHANNES_FLOW_END_QUEUE_CONSUMER   = "main"
	TOPICS_FLOW_STATUS_PENDING               = "bgd-flow-status-pending"
	TOPICS_FLOW_STATUS_PENDING_CONSUMER      = "main"
	TOPICS_FLOW_STATUS_SUBMIT                = "bgd-flow-status-submit"
	TOPICS_FLOW_STATUS_SUBMIT_CONSUMER       = "main"
	TOPICS_FLOW_STATUS_GO                    = "bgd-flow-status-go"
	TOPICS_FLOW_STATUS_GO_CONSUMER           = "main"
	TOPICS_FLOW_STATUS_PENDING_WAIT          = "bgd-flow-status-pending-wait"
	TOPICS_FLOW_STATUS_PENDING_WAIT_CONSUMER = "main"
	TOPICS_FLOW_JOB_QUEUE                    = "bgd-flow-job-queue"
	TOPICS_FLOW_JOB_QUEUE_CONSUMER           = "main"
	TOPICS_FLOW_JOB_SPOOL                    = "bgd-flow-jobspool"
	TOPICS_FLOW_JOB_SPOOL_CONSUMER           = "main"
	TOPICS_FLOW_WORKER                       = "bgd-flow-worker"
	TOPICS_FLOW_WORKER_CONSUMER              = "main"
	TOPICS_FLOW_STATUS_RUNNING               = "bgd-flow-status-running"
	TOPICS_FLOW_STATUS_RUNNING_CONSUMER      = "main"
	TOPICS_FLOW_JOB_RUNNING                  = "bgd-flow-job-running"
	TOPICS_FLOW_JOB_RUNNING_CONSUMER         = "main"
	TOPICS_FLOW_JOB_END                      = "bgd-flow-job-end"
	TOPICS_FLOW_JOB_END_CONSUMER             = "main"
	TOPICS_FLOW_JOB_STREAM                   = "bgd-flow-job-stream"
	TOPICS_FLOW_JOB_STREAM_CONSUMER          = "main"
	TOPICS_FLOW_JOB_LOG                      = "bgd-flow-job-log"
	TOPICS_FLOW_JOB_LOG_CONSUMER             = "main"
)
